### ISSUE TITLE
phone.dat 还在更新吗

### ISSUE THREAD

**Issue by Yinmomo** [xluohome/phonedata#41]
您好 目前的phone.dat截止到2021年8月份 有些号段的当前查不出归属地 想问问您这个文件还在保持更新吗 ？

**Comment by xluohome** [comment]
具体哪些号段无法查询归属地



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月24日(周四) 上午10:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [xluohome/phonedata] phone.dat 还在更新吗 (Issue #41)




 
您好 目前的phone.dat截止到2021年8月份 有些号段的当前查不出归属地 想问问您这个文件还在保持更新吗 ？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Yinmomo** [comment]
感谢您的回复，缺失归属地号段例如电信的193号段，电信的195号段也有部分归属地缺失。



***@***.***
 
发件人： xluohome
发送时间： 2022-03-11 14:26
收件人： xluohome/phonedata
抄送： Yinmomo; Author
主题： Re: [xluohome/phonedata] phone.dat 还在更新吗 (Issue #41)
具体哪些号段无法查询归属地 



---原始邮件--- 
发件人: ***@***.***&gt; 
发送时间: 2022年2月24日(周四) 上午10:01 
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [xluohome/phonedata] phone.dat 还在更新吗 (Issue #41) 





您好 目前的phone.dat截止到2021年8月份 有些号段的当前查不出归属地 想问问您这个文件还在保持更新吗 ？ 

— 
Reply to this email directly, view it on GitHub, or unsubscribe. 
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xluohome** [comment]
后面4位区间是?



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月11日(周五) 下午3:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xluohome/phonedata] phone.dat 还在更新吗 (Issue #41)




 感谢您的回复，缺失归属地号段例如电信的193号段，电信的195号段也有部分归属地缺失。 
 
 
 
 ***@***.*** 
   
 发件人： xluohome 
 发送时间： 2022-03-11 14:26 
 收件人： xluohome/phonedata 
 抄送： Yinmomo; Author 
 主题： Re: [xluohome/phonedata] phone.dat 还在更新吗 (Issue #41) 
 具体哪些号段无法查询归属地  
 
 
 
 ---原始邮件---  
 发件人: ***@***.***&amp;gt;  
 发送时间: 2022年2月24日(周四) 上午10:01  
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;;  
 主题: [xluohome/phonedata] phone.dat 还在更新吗 (Issue #41)  
 
 
 
 
 
 您好 目前的phone.dat截止到2021年8月份 有些号段的当前查不出归属地 想问问您这个文件还在保持更新吗 ？  
 
 —  
 Reply to this email directly, view it on GitHub, or unsubscribe.  
 Triage notifications on the go with GitHub Mobile for iOS or Android.  
 You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&amp;gt;  
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android.  
 You are receiving this because you authored the thread.Message ID: ***@***.***&gt; 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xluohome** [comment]
请下载最新phone.dat库，已更新190，192 等号段数据，如有问题欢迎反馈；
